--<ScriptOptions statementTerminator=";"/>

CREATE TABLE Users (
	USER_STUDENT_NO CHAR(9) NOT NULL,
	USER_PW VARCHAR(25),
	USER_NAME VARCHAR(30) NOT NULL,
	USER_BIRTH VARCHAR(8),
	USER_PHONE VARCHAR(15) NOT NULL,
	USER_MAIL VARCHAR(255) DEFAULT 남자 = M , 여자 F,
	USER_ADDR VARCHAR(255) NOT NULL,
	USER_IMAGE VARCHAR(255) NOT NULL,
	USER_SEX CHAR(1),
	USER_SYS DATETIME,
	USER CHAR(32),
	CURRENT_CONNECTIONS BIGINT NOT NULL,
	TOTAL_CONNECTIONS BIGINT NOT NULL,
	PRIMARY KEY (USER_STUDENT_NO)
);

CREATE UNIQUE INDEX USER ON Users (null);

ALTER TABLE Users ADD PRIMARY KEY (USER_STUDENT_NO);

